system:
  host: rivanna
  dataset_root: "/scratch/dje5dj/car_data"

experiment:
  directive: "a100-80gb"
  gpu_count: "1"
  #profile: ["FisheyeTrafficDarknetLocal"]
  profile: ["FisheyeTrafficUltralyticsLocal"]
  #template: ["yolov4", "yolov7"]
  val_frac: [0.10]
  num_gpus: [1]
  ultra_model: ["yolo11s.pt"]
  repeat: [1,2,3] 

ee:
  identifier: "{experiment.profile}_{experiment.template}_val{experiment.val_frac}"

